export const ADD_TODO = 'ADD_TODO';
export const DELETE_TODO = 'DELETE_TODO';
export const EDIT_TODO = 'EDIT_TODO';
export const COMPLETE_TODO = 'COMPLETE_TODO';
export const COMPLETE_ALL = 'COMPLETE_ALL';
export const CLEAR_COMPLETED = 'CLEAR_COMPLETED';

export const CHECK_SELECTOR = 'CHECK_SELECTOR';
export const CHECK_SELECTOR_FAILED = 'CHECK_SELECTOR_FAILED';
export const CHECK_SELECTOR_SUCCESS = 'CHECK_SELECTOR_SUCCESS';
export const UNCHECK_SELECTOR = 'UNCHECK_SELECTOR';


export const GET_SELECTOR_GRAPH = 'GET_SELECTOR_GRAPH';
export const GET_SELECTOR_GRAPH_FAILED = 'GET_SELECTOR_GRAPH_FAILED';
export const GET_SELECTOR_GRAPH_SUCCESS = 'GET_SELECTOR_GRAPH_SUCCESS';
